"""add social_links to users

Revision ID: 0795f076d25f
Revises: 8fdfe6ff6c34
Create Date: 2025-06-27 21:56:33.421697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0795f076d25f'
down_revision: Union[str, Sequence[str], None] = '8fdfe6ff6c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('social_links', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'social_links')
    # ### end Alembic commands ###
