"""add bio and profile_picture to users

Revision ID: 8fdfe6ff6c34
Revises: 525676092d9a
Create Date: 2025-06-27 17:27:05.538507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fdfe6ff6c34'
down_revision: Union[str, Sequence[str], None] = '525676092d9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_picture')
    op.drop_column('users', 'bio')
    op.drop_table('bookmarks')
    # ### end Alembic commands ###
