"""Renewed DB to include users, bookmarks, and trips

Revision ID: abe5dfd8624a
Revises: bec3ff015cbc
Create Date: 2025-06-29 20:29:05.592296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abe5dfd8624a'
down_revision: Union[str, Sequence[str], None] = 'bec3ff015cbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###
