"""Added banner image attribute

Revision ID: e84f8ccac614
Revises: e780bbb500bc
Create Date: 2025-06-29 21:47:40.474397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e84f8ccac614'
down_revision: Union[str, Sequence[str], None] = 'e780bbb500bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('banner_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'banner_image')
    # ### end Alembic commands ###
